const fs = require('fs');

const languages = {
  zh: {
    dashboard: "仪表板",
    "live-ops": "实时跟踪",
    "staff-registry": "员工登记",
    "guard-profiles": "保安资料",
    "system-users": "系统访问",
    incidents: "事件",
    circulars: "通告",
    "correction-requests": "纠正",
    logout: "注销",
    logged_in_as: "登录为",
    duty: "执勤控制",
    history: "考勤",
    requests: "问题",
    duty_desc: "签到 / 签退",
    history_desc: "您的记录",
    requests_desc: "报告问题",
    incidents_desc: "报告事件",
    circulars_desc: "公告",
    status: "状态",
    on_active_duty: "在岗",
    off_duty: "下岗",
    duty_complete: "执勤完成",
    time_on_duty: "在岗时间",
    allowed_radius: "允许半径",
    inside_zone: "区域内",
    outside_zone: "区域外",
    live_tracking_active: "实时跟踪激活",
    auto_pings: "每5分钟自动Ping",
    ping_now: "立即Ping",
    guard_details: "保安详情",
    name: "姓名",
    today_location: "今日位置",
    today: "今天",
    start_duty: "开始执勤",
    end_duty: "结束执勤",
    sos_panic_alert: "紧急SOS警报",
    acknowledge_alert: "确认警报",
    received: "已收到",
    duty_control: "执勤控制",
    attendance_history: "考勤记录",
    report_issue: "报告问题",
    past_requests: "过去的请求",
    official_announcements: "官方公告",
    records_found: "找到记录",
    no_attendance: "尚无考勤记录",
    no_announcements: "尚无公告",
    no_requests: "未找到过去的请求",
    describe_problem: "描述问题",
    or_record_voice: "或录制语音备忘录",
    tap_to_record: "点击麦克风录音",
    recording: "录音中... 点击停止",
    remove_recording: "删除录音",
    submit_request: "提交给管理员",
    submitting: "提交中...",
    select_language: "选择语言",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  ar: {
    dashboard: "لوحة القيادة",
    "live-ops": "التتبع المباشر",
    "staff-registry": "سجل الموظفين",
    "guard-profiles": "ملفات الحراس",
    "system-users": "وصول النظام",
    incidents: "الحوادث",
    circulars: "التعاميم",
    "correction-requests": "التصحيحات",
    logout: "تسجيل خروج",
    logged_in_as: "تم تسجيل الدخول كـ",
    duty: "مراقبة الواجب",
    history: "الحضور",
    requests: "القضايا",
    duty_desc: "تسجيل الدخول / الخروج",
    history_desc: "سجلك",
    requests_desc: "الإبلاغ عن مشكلة",
    incidents_desc: "الإبلاغ عن الحوادث",
    circulars_desc: "الإعلانات",
    status: "الحالة",
    on_active_duty: "في الخدمة النشطة",
    off_duty: "خارج الخدمة",
    duty_complete: "تم اكتمال الواجب",
    time_on_duty: "وقت الخدمة",
    allowed_radius: "نصف القطر المسموح",
    inside_zone: "داخل المنطقة",
    outside_zone: "خارج المنطقة",
    live_tracking_active: "التتبع المباشر نشط",
    auto_pings: "إشعارات تلقائية كل 5 دقائق",
    ping_now: "إشعار الآن",
    guard_details: "تفاصيل الحارس",
    name: "الاسم",
    today_location: "موقع اليوم",
    today: "اليوم",
    start_duty: "بدء الواجب",
    end_duty: "إنهاء الواجب",
    sos_panic_alert: "تنبيه طوارئ SOS",
    acknowledge_alert: "تأكيد التنبيه",
    received: "تم الاستلام",
    duty_control: "مراقبة الواجب",
    attendance_history: "سجل الحضور",
    report_issue: "الإبلاغ عن مشكلة",
    past_requests: "الطلبات السابقة",
    official_announcements: "إعلانات رسمية",
    records_found: "تم العثور على سجلات",
    no_attendance: "لا توجد سجلات حضور بعد",
    no_announcements: "لا توجد إعلانات بعد",
    no_requests: "لم يتم العثور على طلبات سابقة",
    describe_problem: "صف المشكلة",
    or_record_voice: "أو سجل ملاحظة صوتية",
    tap_to_record: "انقر على الميكروفون للتسجيل",
    recording: "جاري التسجيل... انقر للإيقاف",
    remove_recording: "إزالة التسجيل",
    submit_request: "إرسال إلى المسؤول",
    submitting: "جاري الإرسال...",
    select_language: "اختر اللغة",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  vi: {
    dashboard: "Bảng điều khiển",
    "live-ops": "Theo dõi trực tiếp",
    "staff-registry": "Danh sách nhân viên",
    "guard-profiles": "Hồ sơ bảo vệ",
    "system-users": "Truy cập hệ thống",
    incidents: "Sự cố",
    circulars: "Thông tư",
    "correction-requests": "Chỉnh sửa",
    logout: "Đăng xuất",
    logged_in_as: "Đăng nhập với tên",
    duty: "Kiểm soát nhiệm vụ",
    history: "Điểm danh",
    requests: "Vấn đề",
    duty_desc: "Nhận/Trả ca",
    history_desc: "Lịch sử của bạn",
    requests_desc: "Báo cáo vấn đề",
    incidents_desc: "Báo cáo sự cố",
    circulars_desc: "Thông báo",
    status: "Trạng thái",
    on_active_duty: "Đang làm nhiệm vụ",
    off_duty: "Nghỉ làm",
    duty_complete: "Hoàn thành nhiệm vụ",
    time_on_duty: "Thời gian làm việc",
    allowed_radius: "Bán kính cho phép",
    inside_zone: "Trong khu vực",
    outside_zone: "Ngoài khu vực",
    live_tracking_active: "Theo dõi trực tiếp hoạt động",
    auto_pings: "Tự động ping mỗi 5 phút",
    ping_now: "Ping ngay",
    guard_details: "Chi tiết bảo vệ",
    name: "Tên",
    today_location: "Vị trí hôm nay",
    today: "Hôm nay",
    start_duty: "Bắt đầu nhiệm vụ",
    end_duty: "Kết thúc nhiệm vụ",
    sos_panic_alert: "Báo động SOS khẩn cấp",
    acknowledge_alert: "Xác nhận báo động",
    received: "Đã nhận",
    duty_control: "Kiểm soát nhiệm vụ",
    attendance_history: "Lịch sử điểm danh",
    report_issue: "Báo cáo vấn đề",
    past_requests: "Yêu cầu trước đây",
    official_announcements: "Thông báo chính thức",
    records_found: "bản ghi được tìm thấy",
    no_attendance: "Chưa có bản ghi điểm danh",
    no_announcements: "Chưa có thông báo",
    no_requests: "Không tìm thấy yêu cầu nào",
    describe_problem: "Mô tả vấn đề",
    or_record_voice: "Hoặc ghi âm lời nhắn",
    tap_to_record: "Nhấn mic để ghi âm",
    recording: "Đang ghi âm... nhấn để dừng",
    remove_recording: "Xóa ghi âm",
    submit_request: "Gửi cho Quản trị viên",
    submitting: "Đang gửi...",
    select_language: "Chọn ngôn ngữ",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    "live-ops": "ਲਾਈਵ ਟਰੈਕਿੰਗ",
    "staff-registry": "ਸਟਾਫ ਰਜਿਸਟਰੀ",
    "guard-profiles": "ਗਾਰਡ ਪ੍ਰੋਫਾਈਲ",
    "system-users": "ਸਿਸਟਮ ਐਕਸੈਸ",
    incidents: "ਘਟਨਾਵਾਂ",
    circulars: "ਸਰਕੂਲਰ",
    "correction-requests": "ਸੋਧਾਂ",
    logout: "ਲਾਗ ਆਉਟ",
    logged_in_as: "ਵਜੋਂ ਲਾਗ ਇਨ",
    duty: "ਡਿਊਟੀ ਕੰਟਰੋਲ",
    history: "ਹਾਜ਼ਰੀ",
    requests: "ਸਮੱਸਿਆਵਾਂ",
    duty_desc: "ਚੈੱਕ ਇਨ / ਆਉਟ",
    history_desc: "ਤੁਹਾਡਾ ਇਤਿਹਾਸ",
    requests_desc: "ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    incidents_desc: "ਘਟਨਾ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    circulars_desc: "ਘੋਸ਼ਣਾਵਾਂ",
    status: "ਸਥਿਤੀ",
    on_active_duty: "ਸਰਗਰਮ ਡਿਊਟੀ 'ਤੇ",
    off_duty: "ਡਿਊਟੀ ਬੰਦ",
    duty_complete: "ਡਿਊਟੀ ਪੂਰੀ",
    time_on_duty: "ਡਿਊਟੀ 'ਤੇ ਸਮਾਂ",
    allowed_radius: "ਮਨਜ਼ੂਰ ਘੇਰਾ",
    inside_zone: "ਜ਼ੋਨ ਦੇ ਅੰਦਰ",
    outside_zone: "ਜ਼ੋਨ ਦੇ ਬਾਹਰ",
    live_tracking_active: "ਲਾਈਵ ਟਰੈਕਿੰਗ ਸਰਗਰਮ",
    auto_pings: "ਹਰ 5 ਮਿੰਟ ਵਿੱਚ ਆਟੋ-ਪਿੰਗ",
    ping_now: "ਹੁਣ ਪਿੰਗ ਕਰੋ",
    guard_details: "ਗਾਰਡ ਦੇ ਵੇਰਵੇ",
    name: "ਨਾਮ",
    today_location: "ਅੱਜ ਦਾ ਸਥਾਨ",
    today: "ਅੱਜ",
    start_duty: "ਡਿਊਟੀ ਸ਼ੁਰੂ ਕਰੋ",
    end_duty: "ਡਿਊਟੀ ਖਤਮ ਕਰੋ",
    sos_panic_alert: "ਐਮਰਜੈਂਸੀ SOS ਅਲਰਟ",
    acknowledge_alert: "ਅਲਰਟ ਸਵੀਕਾਰ ਕਰੋ",
    received: "ਪ੍ਰਾਪਤ ਹੋਇਆ",
    duty_control: "ਡਿਊਟੀ ਕੰਟਰੋਲ",
    attendance_history: "ਹਾਜ਼ਰੀ ਦਾ ਇਤਿਹਾਸ",
    report_issue: "ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    past_requests: "ਪਿਛਲੀਆਂ ਬੇਨਤੀਆਂ",
    official_announcements: "ਅਧਿਕਾਰਤ ਘੋਸ਼ਣਾਵਾਂ",
    records_found: "ਰਿਕਾਰਡ ਮਿਲੇ",
    no_attendance: "ਅਜੇ ਕੋਈ ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ ਨਹੀਂ",
    no_announcements: "ਅਜੇ ਕੋਈ ਘੋਸ਼ਣਾ ਨਹੀਂ",
    no_requests: "ਕੋਈ ਪਿਛਲੀ ਬੇਨਤੀ ਨਹੀਂ ਮਿਲੀ",
    describe_problem: "ਸਮੱਸਿਆ ਦਾ ਵਰਣਨ ਕਰੋ",
    or_record_voice: "ਜਾਂ ਵਾਇਸ ਨੋਟ ਰਿਕਾਰਡ ਕਰੋ",
    tap_to_record: "ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਮਾਈਕ ਦਬਾਓ",
    recording: "ਰਿਕਾਰਡ ਹੋ ਰਿਹਾ ਹੈ... ਰੋਕਣ ਲਈ ਦਬਾਓ",
    remove_recording: "ਰਿਕਾਰਡਿੰਗ ਹਟਾਓ",
    submit_request: "ਐਡਮਿਨ ਨੂੰ ਜਮ੍ਹਾਂ ਕਰੋ",
    submitting: "ਜਮ੍ਹਾਂ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    select_language: "ਭਾਸ਼ਾ ਚੁਣੋ",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  el: {
    dashboard: "Πίνακας Ελέγχου",
    "live-ops": "Ζωντανή Παρακολούθηση",
    "staff-registry": "Μητρώο Προσωπικού",
    "guard-profiles": "Προφίλ Φρουρών",
    "system-users": "Πρόσβαση Συστήματος",
    incidents: "Περιστατικά",
    circulars: "Εγκύκλιοι",
    "correction-requests": "Διορθώσεις",
    logout: "Αποσύνδεση",
    logged_in_as: "Συνδεδεμένος ως",
    duty: "Έλεγχος Βάρδιας",
    history: "Παρουσίες",
    requests: "Ζητήματα",
    duty_desc: "Έναρξη / Λήξη Βάρδιας",
    history_desc: "Το Ιστορικό Σας",
    requests_desc: "Αναφορά Προβλήματος",
    incidents_desc: "Αναφορά Περιστατικού",
    circulars_desc: "Ανακοινώσεις",
    status: "Κατάσταση",
    on_active_duty: "Σε Ενεργή Βάρδια",
    off_duty: "Εκτός Βάρδιας",
    duty_complete: "Βάρδια Ολοκληρώθηκε",
    time_on_duty: "Χρόνος Βάρδιας",
    allowed_radius: "Επιτρεπόμενη Ακτίνα",
    inside_zone: "Εντός Ζώνης",
    outside_zone: "Εκτός Ζώνης",
    live_tracking_active: "Ζωντανή Παρακολούθηση Ενεργή",
    auto_pings: "Αυτόματο ping κάθε 5 λεπτά",
    ping_now: "Ping Τώρα",
    guard_details: "Στοιχεία Φρουρού",
    name: "Όνομα",
    today_location: "Σημερινή Τοποθεσία",
    today: "Σήμερα",
    start_duty: "Έναρξη Βάρδιας",
    end_duty: "Λήξη Βάρδιας",
    sos_panic_alert: "Ειδοποίηση SOS",
    acknowledge_alert: "Αναγνώριση Ειδοποίησης",
    received: "Ελήφθη",
    duty_control: "Έλεγχος Βάρδιας",
    attendance_history: "Ιστορικό Παρουσιών",
    report_issue: "Αναφορά Ζητήματος",
    past_requests: "Προηγούμενα Αιτήματα",
    official_announcements: "Επίσημες Ανακοινώσεις",
    records_found: "εγγραφές βρέθηκαν",
    no_attendance: "Δεν υπάρχουν αρχεία παρουσίας",
    no_announcements: "Δεν υπάρχουν ανακοινώσεις",
    no_requests: "Δεν βρέθηκαν προηγούμενα αιτήματα",
    describe_problem: "Περιγράψτε το πρόβλημα",
    or_record_voice: "Ή ηχογραφήστε ένα μήνυμα",
    tap_to_record: "Πατήστε το μικρόφωνο για εγγραφή",
    recording: "Εγγραφή... πατήστε για διακοπή",
    remove_recording: "Αφαίρεση εγγραφής",
    submit_request: "Υποβολή",
    submitting: "Υποβολή...",
    select_language: "Επιλέξτε Γλώσσα",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  it: {
    dashboard: "Dashboard",
    "live-ops": "Tracciamento Live",
    "staff-registry": "Registro Personale",
    "guard-profiles": "Profili Guardie",
    "system-users": "Accesso Sistema",
    incidents: "Incidenti",
    circulars: "Circolari",
    "correction-requests": "Correzioni",
    logout: "Esci",
    logged_in_as: "Accesso effettuato come",
    duty: "Controllo Turno",
    history: "Presenze",
    requests: "Problemi",
    duty_desc: "Check In / Out",
    history_desc: "La tua Cronologia",
    requests_desc: "Segnala Problema",
    incidents_desc: "Segnala Incidente",
    circulars_desc: "Annunci",
    status: "Stato",
    on_active_duty: "In Servizio",
    off_duty: "Fuori Servizio",
    duty_complete: "Servizio Completato",
    time_on_duty: "Tempo in Servizio",
    allowed_radius: "Raggio Consentito",
    inside_zone: "All'interno della Zona",
    outside_zone: "All'esterno della Zona",
    live_tracking_active: "Tracciamento Live Attivo",
    auto_pings: "Auto-ping ogni 5 minuti",
    ping_now: "Ping Ora",
    guard_details: "Dettagli Guardia",
    name: "Nome",
    today_location: "Posizione di Oggi",
    today: "Oggi",
    start_duty: "Inizia Servizio",
    end_duty: "Termina Servizio",
    sos_panic_alert: "Allarme Emergenza SOS",
    acknowledge_alert: "Conferma Allarme",
    received: "Ricevuto",
    duty_control: "Controllo Servizio",
    attendance_history: "Cronologia Presenze",
    report_issue: "Segnala un Problema",
    past_requests: "Richieste Passate",
    official_announcements: "Annunci Ufficiali",
    records_found: "record trovati",
    no_attendance: "Nessun record di presenze",
    no_announcements: "Nessun annuncio",
    no_requests: "Nessuna richiesta passata trovata",
    describe_problem: "Descrivi il problema",
    or_record_voice: "Oppure registra una nota vocale",
    tap_to_record: "Tocca il microfono per registrare",
    recording: "Registrazione... tocca per fermare",
    remove_recording: "Rimuovi registrazione",
    submit_request: "Invia all'Amministratore",
    submitting: "Invio in corso...",
    select_language: "Seleziona Lingua",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  tl: {
    dashboard: "Dashboard",
    "live-ops": "Live na Pagsubaybay",
    "staff-registry": "Talaan ng Staff",
    "guard-profiles": "Mga Profile ng Gwardya",
    "system-users": "Pag-access sa Sistema",
    incidents: "Mga Insidente",
    circulars: "Mga Circular",
    "correction-requests": "Mga Pagwawasto",
    logout: "Mag-logout",
    logged_in_as: "Naka-log in bilang",
    duty: "Kontrol sa Tungkulin",
    history: "Pagdalo",
    requests: "Mga Isyu",
    duty_desc: "Check In / Out",
    history_desc: "Ang Iyong Kasaysayan",
    requests_desc: "Mag-ulat ng Problema",
    incidents_desc: "Mag-ulat ng Insidente",
    circulars_desc: "Mga Anunsyo",
    status: "Katayuan",
    on_active_duty: "Nasa Aktibong Tungkulin",
    off_duty: "Walang Tungkulin",
    duty_complete: "Tapos na ang Tungkulin",
    time_on_duty: "Oras sa Tungkulin",
    allowed_radius: "Pinapayagang Radius",
    inside_zone: "Nasa Loob ng Sona",
    outside_zone: "Nasa Labas ng Sona",
    live_tracking_active: "Aktibo ang Live na Pagsubaybay",
    auto_pings: "Awtomatikong ping bawat 5 minuto",
    ping_now: "I-ping Ngayon",
    guard_details: "Mga Detalye ng Gwardya",
    name: "Pangalan",
    today_location: "Lokasyon Ngayon",
    today: "Ngayon",
    start_duty: "Simulan ang Tungkulin",
    end_duty: "Tapusin ang Tungkulin",
    sos_panic_alert: "Emergency SOS Alerto",
    acknowledge_alert: "Kilalanin ang Alerto",
    received: "Natanggap",
    duty_control: "Kontrol sa Tungkulin",
    attendance_history: "Kasaysayan ng Pagdalo",
    report_issue: "Mag-ulat ng Isyu",
    past_requests: "Mga Nakaraang Kahilingan",
    official_announcements: "Opisyal na Mga Anunsyo",
    records_found: "mga record na natagpuan",
    no_attendance: "Wala pang talaan ng pagdalo",
    no_announcements: "Wala pang anunsyo",
    no_requests: "Walang natagpuang nakaraang kahilingan",
    describe_problem: "Ilarawan ang problema",
    or_record_voice: "O mag-record ng voice note",
    tap_to_record: "I-tap ang mic upang mag-record",
    recording: "Nagre-record... i-tap upang ihinto",
    remove_recording: "Alisin ang recording",
    submit_request: "Isumite sa Admin",
    submitting: "Nagsusumite...",
    select_language: "Pumili ng Wika",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  },
  es: {
    dashboard: "Panel de control",
    "live-ops": "Seguimiento en vivo",
    "staff-registry": "Registro de Personal",
    "guard-profiles": "Perfiles de Guardias",
    "system-users": "Acceso al Sistema",
    incidents: "Incidentes",
    circulars: "Circulares",
    "correction-requests": "Correcciones",
    logout: "Cerrar sesión",
    logged_in_as: "Iniciado como",
    duty: "Control de Guardia",
    history: "Asistencia",
    requests: "Problemas",
    duty_desc: "Entrada / Salida",
    history_desc: "Tu Historial",
    requests_desc: "Reportar Problema",
    incidents_desc: "Reportar Incidente",
    circulars_desc: "Anuncios",
    status: "Estado",
    on_active_duty: "En Servicio Activo",
    off_duty: "Fuera de Servicio",
    duty_complete: "Servicio Completado",
    time_on_duty: "Tiempo en servicio",
    allowed_radius: "Radio Permitido",
    inside_zone: "Dentro de la Zona",
    outside_zone: "Fuera de la Zona",
    live_tracking_active: "Seguimiento en vivo activo",
    auto_pings: "Ping automático cada 5 mins",
    ping_now: "Ping Ahora",
    guard_details: "Detalles del Guardia",
    name: "Nombre",
    today_location: "Ubicación de hoy",
    today: "Hoy",
    start_duty: "Iniciar Servicio",
    end_duty: "Finalizar Servicio",
    sos_panic_alert: "Alerta SOS de Emergencia",
    acknowledge_alert: "Confirmar Alerta",
    received: "Recibido",
    duty_control: "Control de Servicio",
    attendance_history: "Historial de Asistencia",
    report_issue: "Reportar un Problema",
    past_requests: "Solicitudes Pasadas",
    official_announcements: "Anuncios Oficiales",
    records_found: "registros encontrados",
    no_attendance: "Aún no hay registros de asistencia",
    no_announcements: "Aún no hay anuncios",
    no_requests: "No se encontraron solicitudes",
    describe_problem: "Describe el problema",
    or_record_voice: "O graba una nota de voz",
    tap_to_record: "Toca el micrófono para grabar",
    recording: "Grabando... toca para detener",
    remove_recording: "Eliminar grabación",
    submit_request: "Enviar al Admin",
    submitting: "Enviando...",
    select_language: "Seleccionar Idioma",
    english: "English",
    hindi: "Hindi (हिंदी)",
    tamil: "Tamil (தமிழ்)",
    telugu: "Telugu (తెలుగు)",
    kannada: "Kannada (ಕನ್ನಡ)",
    zh: "Mandarin (中文)",
    ar: "Arabic (العربية)",
    vi: "Vietnamese (Tiếng Việt)",
    pa: "Punjabi (ਪੰਜਾਬੀ)",
    el: "Greek (Ελληνικά)",
    it: "Italian (Italiano)",
    tl: "Tagalog",
    es: "Spanish (Español)"
  }
};

const file = fs.readFileSync('src/LanguageContext.jsx', 'utf-8');
const newFile = file.replace('};', ',\n' + JSON.stringify(languages, null, 2).slice(2, -2) + '\n};');
fs.writeFileSync('src/LanguageContext.jsx', newFile);
